version: '3'
services:
  cmake:
    build:
      context: .
      dockerfile: Dockerfile.cmake
    image: aztecprotocol/cmake:3.15.4

  clang:
    build:
      context: .
      dockerfile: Dockerfile.clang
    image: aztecprotocol/clang:9.0.0

  x86-gcc-openmp:
    build:
      context: .
      dockerfile: Dockerfile.x86-gcc-openmp
    image: aztecprotocol/barretenberg:x86-gcc-openmp
    tty: true
    environment:
      MAKEFLAGS: '-j8'

  x86-clang-openmp:
    build:
      context: .
      dockerfile: Dockerfile.x86-clang-openmp
    image: aztecprotocol/barretenberg:x86-clang-openmp
    tty: true
    environment:
      MAKEFLAGS: '-j8'

  x86_64-win32:
    build:
      context: .
      dockerfile: Dockerfile.x86-mxe
    image: aztecprotocol/barretenberg:x86_64-win32
    tty: true
    environment:
      MAKEFLAGS: '-j8'
