version: '3'
services:
  cmake:
    build:
      context: .
      dockerfile: Dockerfile.cmake
    image: aztecprotocol/cmake:3.15.4

  linux-openmp:
    build:
      context: .
      dockerfile: Dockerfile.linux-openmp
    image: aztecprotocol/barretenberg:linux-openmp
    tty: true
    environment:
      MAKEFLAGS: '-j8'
    volumes:
      - .:/usr/src/barretenberg
