version: '3'
services:
  ganache:
    image: trufflesuite/ganache
    environment:
      NODE_OPTIONS: --max_old_space_size=3072
    command: -h='0.0.0.0' -q -l 15000000 -e 10000 -m='test test test test test test test test test test test junk' ${CHAIN_ID} ${FORK_HOST} ${FORK_BLOCK}
    ports:
      - '8545:8545'

  halloumi1:
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/halloumi:latest
    environment:
      NODE_ENV: production
      NUM_INNER_ROLLUP_TXS: ${NUM_INNER_ROLLUP_TXS}
      NUM_OUTER_ROLLUP_PROOFS: ${NUM_OUTER_ROLLUP_PROOFS}
      PERSIST: 'false'
      PROVERLESS: ${PROVERLESS}
      JOB_SERVER_URL: http://falafel:8082

  halloumi2:
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/halloumi:latest
    environment:
      NODE_ENV: production
      NUM_INNER_ROLLUP_TXS: ${NUM_INNER_ROLLUP_TXS}
      NUM_OUTER_ROLLUP_PROOFS: ${NUM_OUTER_ROLLUP_PROOFS}
      PERSIST: 'false'
      PROVERLESS: ${PROVERLESS}
      JOB_SERVER_URL: http://falafel:8082

  falafel:
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/falafel:latest
    environment:
      ETHEREUM_HOST: http://ganache:8545
      NUM_INNER_ROLLUP_TXS: ${NUM_INNER_ROLLUP_TXS}
      NUM_OUTER_ROLLUP_PROOFS: ${NUM_OUTER_ROLLUP_PROOFS}
      BASE_TX_GAS: 10000
      PUBLISH_INTERVAL: 120
      NODE_ENV: production
      PROVERLESS: ${PROVERLESS}
      VK: ${VK}
      FEE_PAYING_ASSET_IDS: 0,1
      FEE_GAS_PRICE_MULTIPLIER: 0.01
    depends_on:
      - ganache
    command: >
      sh -c "
      while ! nc -z ganache 8545; do sleep 1; done;
      `yarn -s deploy_rollup_processor`;
      yarn start
      "
    ports:
      - '8081:8081'

  sdk:
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/sdk:latest
    depends_on:
      - falafel
    command: >
      sh -c "
      echo http://falafel:8081 > /usr/src/sdk/dist/ROLLUP_PROVIDER_URL;
      yarn start
      "
    ports:
      - '1234:1234'

  hummus:
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/hummus:latest
    depends_on:
      - sdk
    ports:
      - '8080:8080'

  end-to-end:
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/end-to-end:latest
    environment:
      ETHEREUM_HOST: http://ganache:8545
      ROLLUP_HOST: http://falafel:8081
      SDK_HOST: http://sdk:1234
      HUMMUS_HOST: http://hummus:8080
      PROVERLESS: ${PROVERLESS}
    depends_on:
      - hummus
    command: >
      sh -c "
      apk add curl jq bash;
      ./scripts/wait_till_ready;
      yarn test ${TEST:-./src/e2e.test.ts}
      "
