packageExtensions:
  '@apollo/react-components@*':
    dependencies:
      '@types/prop-types': '*'
  '@apollo/react-hoc@*':
    dependencies:
      apollo-cache: '*'
      apollo-link: '*'
      apollo-utilities: '*'
  '@apollo/react-hooks@*':
    dependencies:
      '@types/zen-observable': '*'
      apollo-link: '*'
      apollo-utilities: '*'
  '@apollo/react-ssr@*':
    dependencies:
      apollo-client: '*'
      apollo-link: '*'
      apollo-utilities: '*'
      graphql: 14.3.1
  '@aztec/bridge-clients@*':
    dependencies:
      '@ethersproject/abi': 5.5.0
      ethers: 5.5.0
      tslib: '*'
  '@walletconnect/iso-crypto@*':
    dependencies:
      '@walletconnect/encoding': '*'
  '@web3-react/core@*':
    dependencies:
      '@ethersproject/bytes': '*'
  apollo-boost@*:
    dependencies:
      graphql: ^15.0.0
  apollo-client@*:
    dependencies:
      graphql: ^15.0.0
  apollo-link-error@*:
    dependencies:
      graphql: ^15.0.0
  react-apollo@*:
    dependencies:
      apollo-cache: '*'
      apollo-link: '*'
      apollo-utilities: '*'
      graphql: ^14.3.1
  react-router-dom@*:
    dependencies:
      '@remix-run/router': '*'
  sass-loader@*:
    dependencies:
      sass: '*'
  styled-components@*:
    dependencies:
      babel-plugin-macros: '*'
      react-is: '*'
  type-graphql@*:
    dependencies:
      graphql: ^15.0.0
  wagmi@*:
    dependencies:
      react-dom: '*'
  chalk@5.0.1:
    dependencies:
      '#ansi-styles': npm:ansi-styles@6.1.0
      '#supports-color': npm:supports-color@9.2.2
  json-normalize@*:
    dependencies:
      'source-map-support': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
