version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli
    environment:
      NODE_OPTIONS: --max_old_space_size=3072
    command:
      ['-a=10', '-h=0.0.0.0', '--chainId=1337', '-q', 'm=test test test test test test test test test test test junk']
    ports:
      - '8545:8545'

  falafel:
    build: ../falafel
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/falafel:latest
    environment:
      ETHEREUM_HOST: http://ganache:8545
      NODE_ENV: production
      TX_FEE: 100000000000000000
    depends_on:
      - ganache
    command: >
      sh -c "
      while ! nc -z ganache 8545; do sleep 1; done;
      `yarn -s deploy_rollup_processor`;
      yarn start
      "
    ports:
      - '8081:8081'

  end-to-end:
    build: .
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/end-to-end:latest
    environment:
      ETHEREUM_HOST: http://ganache:8545
      ROLLUP_HOST: http://falafel:8081
    depends_on:
      - falafel
    command: >
      sh -c "
      while ! nc -z falafel 8081; do sleep 1; done;
      yarn test ./src/e2e.test.ts
      "
