version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli
    environment:
      NODE_OPTIONS: --max_old_space_size=3072
    command:
      [
        '-h=0.0.0.0',
        '--chainId=1337',
        '-q',
        '-l 12000000',
        '-e 10000',
        '-m=test test test test test test test test test test test junk',
      ]
    ports:
      - '8545:8545'

  halloumi:
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/halloumi:latest
    environment:
      NODE_ENV: production
      PERSIST: 'false'
    ports:
      - '8083:8083'

  falafel:
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/falafel:latest
    environment:
      ETHEREUM_HOST: http://ganache:8545
      HALLOUMI_HOST: http://halloumi:8083
      NUM_OUTER_ROLLUP_PROOFS: 2
      NODE_ENV: production
      TX_FEE: 100000000000000000
    depends_on:
      - ganache
      - halloumi
    command: >
      sh -c "
      while ! nc -z ganache 8545; do sleep 1; done;
      `yarn -s deploy_rollup_processor`;
      yarn start
      "
    ports:
      - '8081:8081'

  end-to-end:
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/end-to-end:latest
    environment:
      ETHEREUM_HOST: http://ganache:8545
      ROLLUP_HOST: http://falafel:8081
    depends_on:
      - falafel
    command: >
      sh -c "
      apk add curl jq bash;
      ./scripts/wait_till_ready.sh;
      yarn test ${TEST:-./src/e2e.test.ts}
      "
