[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc_version = '0.8.10'
optimizer = true
optimizer_runs = 100000
remappings = [
    'ac/=contracts/', 
    'forge-std/=lib/forge-std/src',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/', 
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@uniswap/=node_modules/@uniswap/',
    ]

eth_rpc_url = "https://mainnet.infura.io/v3/9928b52099854248b3a096be07a6b23c"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config