#!/bin/bash
# Launches tmux with 4 panes running, from top-left, top-right, bottom-left, bottom-right:
# - kebab
# - falafel
# - block-server
# - halloumi
TEST=$1
SESSION_NAME=aztec-clean-build

cd $(git rev-parse --show-toplevel)

if tmux has-session -t $SESSION_NAME > /dev/null 2>&1; then
  tmux attach -t $SESSION_NAME
else
  tmux new-session -s $SESSION_NAME -d
  tmux split-window \; \
  select-layout tiled \; \
  split-window \; \
  select-layout tiled \; \
  split-window \; \
  select-layout tiled \; \
  # Give a chance for terminals to start (avoids double command echo).
  sleep 3
  tmux select-pane -t 0 \; \
  send-keys 'cd yarn-project/kebab && yarn clean && yarn build' C-m \; \
  select-pane -t 1 \; \
  send-keys 'cd yarn-project/falafel && yarn clean && yarn build' C-m \; \
  select-pane -t 2 \; \
  send-keys 'cd yarn-project/block-server && yarn clean && yarn build' C-m \; \
  select-pane -t 3 \; \
  send-keys 'cd yarn-project/halloumi && yarn clean && yarn build' C-m \; \
  attach \;
fi
